manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    - name: zmk-ws2812-driver
      url: https://github.com/gohanda11/zmk-ws2812-driver.git
      revision: main
      path: modules/zmk-ws2812-driver
  self:
    path: config
    west-commands: modules/zmk-ws2812-driver/scripts

